---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: myapp-rs
  labels:
    type: myapp-rs-label  
spec:
  replicas: 1
  selector:
    matchLabels:
      type: myapp
    matchExpressions:
      - {key: type, operator: In, values: [myapp]}  
  template:
    metadata:
      labels:
        type: myapp
    spec:
      containers:
      - name: frontend
        image: salrashid123/myapp
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /_ah/health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
        env:
        - name: CUR_TYPE
          value: metadata.labels.type   
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP                    


