apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: app
  ports:
  - name: http-port
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    type: app-service
spec:
  replicas: 1
  selector:
    matchLabels:
      type: app-service
  template:
    metadata:
      labels:
        type: app-service
        app.kubernetes.io/name: app
    spec:
      containers:
      - name: service
        image: docker.io/salrashid123/simplegcsapp@sha256:d6347483a3c5cb200fbf2490e95cfcd1edd5ff79bbc9c6080d598b206e4a9ae5     
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP 
        env:
        - name: GCE_METADATA_HOST
          value: "metadata-service:8080"
